- name: Set facts
  hosts: all
  gather_facts: true
  order: "{{ pb_order | d('sorted') }}"
  strategy: "{{ pb_strategy | d('linear') }}"
  serial: "{{ pb_serial | d(omit) }}"
  tasks:
    - name: Create the custom.fact file with JSON content
      copy:
        dest: /etc/ansible/facts.d/custom.fact
        content: |
          {
            "status": "active",
            "version": "1.2.3"
          }
