- name: Set facts
  hosts: 192.168.64.105
  gather_facts: true
  tasks:
    - name: set facts
      ansible.builtin.lineinfile:
        line: '"aap_version": "2.5.0"'
        file: /etc/ansible/facts.d/custom.fact
