---
- name: Discover AWX Path via Running Processes
  hosts: localhost
  become: true
  tasks:
    - name: Get path from running awx/automation-controller processes
      shell: |
        ps -ef | grep -E 'awx|automation-controller' | grep -v grep | awk '{print $8}' | grep 'python' | head -n 1
      register: process_path
      failed_when: process_path.stdout == ""

    - name: Derive management binary path
      set_fact:
        # This takes the python path and looks for the manage command in the same bin folder
        mgmt_bin: "{{ process_path.stdout | dirname }}/awx-manage"
      
    - name: Verify if derived binary exists
      stat:
        path: "{{ mgmt_bin }}"
      register: bin_check

    - name: Try alternative name (Automation Controller)
      set_fact:
        mgmt_bin: "{{ process_path.stdout | dirname }}/automation-controller-manage"
      when: not bin_check.stat.exists

    - name: Run analytics collection
      shell: "{{ mgmt_bin }} gather_analytics --ship"
      become_user: awx
      register: analytics_output

    - name: Report
      debug:
        var: analytics_output.stdout_lines
