---
- name: Dynamic AWX/AAP Analytics Collection
  hosts: localhost
  become: true
  tasks:
    - name: Locate the management binary
      shell: |
        which automation-controller-manage || \
        which awx-manage || \
        ls /usr/bin/automation-controller-manage || \
        ls /usr/bin/awx-manage || \
        ls /var/lib/awx/venv/awx/bin/awx-manage
      register: mgmt_path_raw
      failed_when: mgmt_path_raw.rc != 0
      changed_when: false

    - name: Set management path variable
      set_fact:
        mgmt_bin: "{{ mgmt_path_raw.stdout_lines[0] }}"

    - name: Run analytics collection as 'awx' user
      shell: "{{ mgmt_bin }} gather_analytics --ship"
      become_user: awx
      register: analytics_output
      changed_when: "'Committed' in analytics_output.stdout"

    - name: Report Results
      debug:
        msg: 
          - "Binary used: {{ mgmt_bin }}"
          - "Output: {{ analytics_output.stdout }}"
