---
- name: Test
  connection: local
  hosts: 192.168.64.57
  tasks:    
    - name: Run query to get /var size
      shell: df -h /var/
      register: disk_usage
     # become: true


    - name: Run query to get /var/lib size
      shell: df -h /var/lib/
      register: disk_usage
     # become: true

    - name: Run query to get var lib awx size
      shell: df -h /var/lib/awx/
      register: disk_usage
     # become: true
      
    - name: Show disk space
      debug:
        msg: "/var/lib/awx diskspace is: {{ disk_usage }}"
