---
- name: Execute Internal Analytics Gathering
  hosts: all  # Point this to your actual controller host in your inventory
  become: true             # awx-manage usually requires root/awx user perms
  gather_facts: false
  
  tasks:
    - name: Trigger analytics collection
      ansible.builtin.shell:
        # We use the full path to avoid 'command not found'
        cmd: /usr/bin/awx-manage gather_analytics --ship
      register: analytics_result

    - name: Report Status
      ansible.builtin.debug:
        var: analytics_result.stdout_lines
