---
- name: Locate AWX via Python Internals
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Ask Python where the AWX package is located
      shell: |
        python3 -c "import awx; import os; print(os.path.dirname(awx.__file__))"
      register: awx_lib_path
      ignore_errors: true

    - name: Find the manage.py script relative to the library
      shell: |
        find {{ awx_lib_path.stdout | default('/usr') }} -name "manage.py" | head -n 1
      register: manage_py_path
      when: awx_lib_path.rc == 0

    - name: Run analytics using the discovered manage.py
      shell: "python3 {{ manage_py_path.stdout }} gather_analytics --ship"
      become_user: awx
      when: manage_py_path.stdout is defined and manage_py_path.stdout != ""
      register: manual_run

    - name: Success check
      debug:
        msg: "Found and executed: {{ manage_py_path.stdout }}"
      when: manual_run is not skipped
