---
- name: Force Locate and Run Analytics
  hosts: localhost
  become: true
  tasks:
    - name: Search filesystem for the management binary
      shell: |
        find /usr /opt /var -name "awx-manage" -executable -o -name "automation-controller-manage" -executable 2>/dev/null | head -n 1
      register: found_path
      failed_when: found_path.stdout == ""

    - name: Set management path
      set_fact:
        mgmt_bin: "{{ found_path.stdout.trim() }}"

    - name: Run analytics collection
      shell: "{{ mgmt_bin }} gather_analytics --ship"
      become_user: awx
      register: analytics_output

    - name: Show success
      debug:
        msg: "Successfully ran {{ mgmt_bin }}"
