---
- name: Trigger AWX Analytics Collection on Host
  hosts: localhost
  become: true
  vars:
    # Common path for RPM-based installations
    awx_venv_path: "/var/lib/awx/venv/awx"

  tasks:
    - name: Ensure awx-manage exists at the expected path
      stat:
        path: "{{ awx_venv_path }}/bin/awx-manage"
      register: awx_binary

    - name: Run gather_analytics via host virtualenv
      shell: |
        source {{ awx_venv_path }}/bin/activate
        awx-manage gather_analytics --ship
      become_user: awx
      when: awx_binary.stat.exists
      register: analytics_output

    - name: Fail if awx-manage not found
      fail:
        msg: "awx-manage not found at {{ awx_venv_path }}. Please verify your installation path."
      when: not awx_binary.stat.exists

    - name: Display execution results
      debug:
        msg: "{{ analytics_output.stdout_lines }}"
