---
- name: Execute Internal Analytics Gathering
  hosts: localhost
  connection: local
  gather_facts: false
  
  tasks:
    - name: Trigger analytics collection and shipment
      ansible.builtin.command:
        cmd: awx-manage gather_analytics --ship
      register: analytics_result
      # Use changed_when to avoid 'always yellow' status if you prefer
      changed_when: "'Committed' in analytics_result.stdout"

    - name: Report Status
      ansible.builtin.debug:
        msg: 
          - "Analytics Task Output:"
          - "{{ analytics_result.stdout }}"
