---
- name: Gather and Ship AWX Analytics
  hosts: localhost
  connection: local
  gather_facts: false
  tasks:
    - name: Run awx-manage command
      ansible.builtin.command:
        cmd: podman exec -u 0 -t awx awx-manage gather_analytics --ship
      become: yes # May require privilege escalation if the default user lacks permissions

