   - name: Delete /tmp/test directory and all its contents
     ansible.builtin.file:
       path: /tmp/test
       state: absent
     delegate_to: localhost
     connection: local
     run_once: true
